'use strict';
const screens=[...document.querySelectorAll('.screen')],pagesEl=document.getElementById('calendarPages'),dotsEl=document.getElementById('pageDots'),giftPagesEl=document.getElementById('giftPages'),giftDotsEl=document.getElementById('giftDots'),curtain=document.getElementById('heartCurtain'),music=document.getElementById('music'),soundBtn=document.getElementById('soundBtn'),storyStage=document.getElementById('storyStage');
const STORAGE='mama-kalender-2026-2027-v1';let entries={};try{entries=JSON.parse(localStorage.getItem(STORAGE)||'{}')}catch{entries={}}const save=()=>localStorage.setItem(STORAGE,JSON.stringify(entries));
const months=['Januar','Februar','März','April','Mai','Juni','Juli','August','September','Oktober','November','Dezember'],weekdays=['So','Mo','Di','Mi','Do','Fr','Sa'],romans=['I','II','III'],pad=n=>String(n).padStart(2,'0'),key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
let storyTimers=[];function clearStory(){storyTimers.forEach(clearTimeout);storyTimers=[];storyStage.innerHTML=''}const later=(fn,ms)=>storyTimers.push(setTimeout(fn,ms));
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));if(id==='album')startTypewriter();if(id!=='giftStory')clearStory()}
function heartTransition(target){curtain.innerHTML='';for(let i=0;i<36;i++){const h=document.createElement('span');h.className='fall-heart';h.textContent='♥';h.style.left=`${(i%9)*12-2}%`;h.style.fontSize=`${55+(i%5)*18}px`;h.style.animationDelay=`${Math.floor(i/9)*.08+(i%3)*.025}s`;curtain.appendChild(h)}setTimeout(()=>show(target),420);setTimeout(()=>curtain.innerHTML='',1450)}
function addDot(t){const d=document.createElement('span');d.className='dot';t.appendChild(d)}
// Pager fix: fixed viewport + pixel transform. No %-translation of an oversized flex track, no scroll handler, one swipe = one page.
function createPager(track,dots){let index=0,sx=0,sy=0,tracking=false,busy=false;const viewport=track.parentElement;function width(){return Math.max(1,viewport.clientWidth)}function render(animate=true){busy=animate;track.style.transition=animate?'transform .32s cubic-bezier(.22,.8,.3,1)':'none';track.style.transform=`translate3d(${-index*width()}px,0,0)`;[...dots.children].forEach((d,i)=>d.classList.toggle('on',i===index));if(animate)setTimeout(()=>busy=false,340)}
track.addEventListener('touchstart',e=>{if(busy||e.touches.length!==1)return;tracking=true;sx=e.touches[0].clientX;sy=e.touches[0].clientY},{passive:true});track.addEventListener('touchcancel',()=>tracking=false,{passive:true});track.addEventListener('touchend',e=>{if(!tracking||busy)return;tracking=false;const dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.abs(dx)>48&&Math.abs(dx)>Math.abs(dy)*1.2){index=Math.max(0,Math.min(track.children.length-1,index+(dx<0?1:-1)));render(true)}},{passive:true});window.addEventListener('resize',()=>render(false),{passive:true});render(false);return{reset(){index=0;requestAnimationFrame(()=>render(false))}}}
function buildCalendar(){const end=new Date(2027,8,21);let cursor=new Date(2026,8,1);while(cursor<=end){const y=cursor.getFullYear(),m=cursor.getMonth(),last=new Date(y,m+1,0).getDate();let ranges;if(y===2026&&m===8)ranges=[[21,30,2]];else if(y===2027&&m===8)ranges=[[1,10,0],[11,20,1],[21,21,2]];else ranges=[[1,10,0],[11,20,1],[21,last,2]];ranges.forEach(([from,to,ri])=>{const p=document.createElement('article');p.className='month-page';p.innerHTML=`<h2 class="month-title">${months[m]} ${y}</h2><div class="roman">${romans[ri]}</div><div class="days"></div>`;const days=p.querySelector('.days');for(let day=from;day<=to;day++){const d=new Date(y,m,day),k=key(d),row=document.createElement('div');row.className='day-row';const lab=document.createElement('div');lab.className='day-label'+([0,6].includes(d.getDay())?' weekend':'');lab.innerHTML=`${weekdays[d.getDay()]}, ${pad(day)}.${pad(m+1)}.${day===21&&m===8?' <span class="cake">🎂</span>':''}`;const input=document.createElement('input');input.className='day-input';input.type='text';input.inputMode='text';input.autocomplete='off';input.value=entries[k]||'';input.addEventListener('input',()=>{entries[k]=input.value;save()});row.append(lab,input);days.appendChild(row)}pagesEl.appendChild(p);addDot(dotsEl)});cursor=new Date(y,m+1,1)}}
function buildGifts(){let cursor=new Date(2026,8,1),end=new Date(2027,8,1);while(cursor<=end){const y=cursor.getFullYear(),m=cursor.getMonth(),unlocked=y===2026&&m===8,p=document.createElement('article');p.className='gift-page'+(unlocked?'':' locked');p.innerHTML=`<h2 class="gift-month">${months[m]} ${y}</h2><div class="gift-choice"><button class="choice choice-a">A</button><button class="choice choice-b">B</button>${unlocked?'':'<div class="lock-overlay">🔒</div>'}</div>`;if(unlocked){p.querySelector('.choice-a').addEventListener('click',playOptionA);p.querySelector('.choice-b').addEventListener('click',playOptionB)}else p.querySelectorAll('.choice').forEach(b=>b.disabled=true);giftPagesEl.appendChild(p);addDot(giftDotsEl);cursor=new Date(y,m+1,1)}}
let typingTimer;function startTypewriter(){clearInterval(typingTimer);const t=document.getElementById('typewriterText'),h=document.querySelector('.album-heart'),text='Hier werden zukünftig Bilder, die wir auf den Ausflügen schießen, hinterlegt.';let i=0;t.textContent='';t.classList.add('typing-caret');h.classList.remove('show');typingTimer=setInterval(()=>{t.textContent+=text[i++]||'';if(i>=text.length){clearInterval(typingTimer);t.classList.remove('typing-caret');h.classList.add('show')}},110)}
function frame(src,klass=''){const im=document.createElement('img');im.className='story-image '+klass;im.src=src;return im}function caption(txt,klass=''){const d=document.createElement('div');d.className='story-caption '+klass;d.textContent=txt;return d}function setFrame(src){let old=storyStage.querySelector('.story-image.current');const im=frame(src,'current');storyStage.appendChild(im);requestAnimationFrame(()=>im.classList.add('visible'));if(old){old.classList.remove('visible');later(()=>old.remove(),900)}}
function typeCaption(text){const d=caption('','type-story');storyStage.appendChild(d);let i=0;const tick=()=>{if(i<text.length){d.textContent+=text[i++];later(tick,42)}};tick();return d}
function playOptionA(){clearStory();show('giftStory');setFrame('assets/a1.png');const c=typeCaption('OPTION A: Wanderung mit Start am Teufelsschuppen und dortigem Picknick.');later(()=>{setFrame('assets/a2.png');c.remove();typeCaption('Ziel 1: Bärenburg - Ramsbach.')},5000);later(()=>{setFrame('assets/a3.png');storyStage.querySelectorAll('.story-caption').forEach(x=>x.remove());typeCaption('Ziel 2: Ruine Neuenstein - Hubacker')},10000)}
function playOptionB(){clearStory();show('giftStory');setFrame('assets/a4.png');const film=caption('FILMABEND!','film-title');storyStage.appendChild(film);requestAnimationFrame(()=>film.classList.add('visible'));later(()=>setFrame('assets/a5.png'),2000);later(()=>setFrame('assets/a6.png'),4000);later(()=>{film.classList.remove('visible');later(()=>film.remove(),650);const c=caption('Für Pasta und Snacks wird gesorgt.','food-copy');storyStage.appendChild(c);requestAnimationFrame(()=>c.classList.add('visible'));later(()=>{c.classList.remove('visible');later(()=>{c.remove();const food=document.createElement('div');food.className='food-pair';food.append(frame('assets/a7.png'),frame('assets/a8.png'));storyStage.appendChild(food);requestAnimationFrame(()=>food.classList.add('visible'))},700)},3000)},6000)}
function tryPlay(){if(!music.muted)music.play().catch(()=>{})}buildCalendar();buildGifts();const calendarPager=createPager(pagesEl,dotsEl),giftPager=createPager(giftPagesEl,giftDotsEl);document.getElementById('calendarBtn').onclick=()=>{calendarPager.reset();heartTransition('calendar');tryPlay()};document.getElementById('albumBtn').onclick=()=>{heartTransition('album');tryPlay()};document.getElementById('giftBtn').onclick=()=>{giftPager.reset();heartTransition('gift');tryPlay()};document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>heartTransition('home'));soundBtn.onclick=()=>{music.muted=!music.muted;soundBtn.textContent=music.muted?'🔇':'🔊';if(!music.muted)tryPlay()};document.addEventListener('pointerdown',tryPlay,{once:true});setTimeout(()=>{document.querySelector('.heart-draw').classList.add('done');soundBtn.classList.remove('hidden');heartTransition('home');tryPlay()},4400);
